### Quality of Life Explorer 

##### Import Libraries

- To run this script we need the libraries below
- Pandas : For creating DataFrames
- Numpy:  For computations 
- OS : For modifying working directories 
- censusdata: This is a library for accessing US Census Bureau, we use some of its function to preview variables *
- Census: Main library for accessing the US Census Bureau API *
- pd.set_option allows us to view our entire output instead of it being truncated in jupyter notebook



 * You need to install these packages before you can use. Census = pip install census | censusdata = pip install CensusData

In [3]:
import pandas as pd
import numpy as np
import os
import censusdata as cs
from census import Census
pd.set_option('display.max_rows',None, 'display.max_columns',None,'display.max_colwidth', None)

##### Set Directory 

- Jupyter notebooks have default directories 
- Use os.chdir to set your preferred directory

In [2]:
path = "C:\\Users\\padu\\Desktop\\UrbanInstitute\\CensusData"
os.chdir(path)

In [3]:
pwd

'C:\\Users\\padu\\Downloads'

##### Pass your API Key

- Go to this [website](https://api.census.gov/data/key_signup.html 'sign up for your personal API key') and sign up your personal API key 

- Once you get your API key, call the Census function and pass your API key. Eg. Census("API Key") 

In [4]:
c = Census("e0577a26a616f4dda60446eae987e3b6d0d944a3")

#### Preview ACS variable 
- Use the censustable function from censusdata library to preview the census variables
- To preview specify the dataset type eg. ACS year 5 estimates (acs5), then the year of interest(2019), then the table number('B21001')
- Use the printtable function to format the output nicely 

In [9]:
cs.printtable(cs.censustable('acs5',2019,'B03002'))

Variable     | Table                          | Label                                                    | Type 
-------------------------------------------------------------------------------------------------------------------
B03002_001E  | HISPANIC OR LATINO ORIGIN BY R | !! Estimate Total:                                       | int  
B03002_002E  | HISPANIC OR LATINO ORIGIN BY R | !! !! Estimate Total: Not Hispanic or Latino:            | int  
B03002_003E  | HISPANIC OR LATINO ORIGIN BY R | !! !! !! Estimate Total: Not Hispanic or Latino: White a | int  
B03002_004E  | HISPANIC OR LATINO ORIGIN BY R | !! !! !! Estimate Total: Not Hispanic or Latino: Black o | int  
B03002_005E  | HISPANIC OR LATINO ORIGIN BY R | !! !! !! Estimate Total: Not Hispanic or Latino: America | int  
B03002_006E  | HISPANIC OR LATINO ORIGIN BY R | !! !! !! Estimate Total: Not Hispanic or Latino: Asian a | int  
B03002_007E  | HISPANIC OR LATINO ORIGIN BY R | !! !! !! Estimate Total: Not Hispanic or Lati

#### Downloading ACS data 
- We use the census library to download ACS variables for the census API. 
- We are able to access the census API because we passed our unique API key in the step above
- To access the data with census library, we have to specify the dataset of interest(acs5) and call the 'get' function
- The get function needs few key parameters including : NAME, ACS variable ID, geography of interest, and year of interest

    - Name: The name parameter reports the census block name
    
    - ACS Variable: The variable has to be specific, Estimates has E at the end, Margion of Error has M 
    
    - Geography: The geography uses a python dictionary.i.e key value pairs. we are interested in all blockgroup in Mecklenburg county. To get those we have to specify the geography using (for:name of geography and asteriks since we want all blockgroups), then for the county we have to specify the State ID (NC ID is 37) and the County ID (Meck County ID is 119), then the year (2019)
    
- The output after running the get function is a dictionary, so we wrap it in pandas DataFrame for further analysis

In [10]:
Data = pd.DataFrame(c.acs5.get(('NAME',
                                ###
                                'B28011_004E', 'B28011_004M', 'B28011_001E','B28011_001M'
                                ######################### Median ##################################
                               ),{'for':'block group:*',
                                   'in':'state:37 county:119'}, year = 2020))
# Data

In [11]:
Data

NAME  \
0     Block Group 2, Census Tract 1.01, Mecklenburg County, North Carolina   
1     Block Group 1, Census Tract 1.03, Mecklenburg County, North Carolina   
2        Block Group 1, Census Tract 8, Mecklenburg County, North Carolina   
3        Block Group 2, Census Tract 9, Mecklenburg County, North Carolina   
4       Block Group 1, Census Tract 11, Mecklenburg County, North Carolina   
5       Block Group 1, Census Tract 12, Mecklenburg County, North Carolina   
6       Block Group 1, Census Tract 13, Mecklenburg County, North Carolina   
7       Block Group 1, Census Tract 14, Mecklenburg County, North Carolina   
8    Block Group 2, Census Tract 15.04, Mecklenburg County, North Carolina   
9    Block Group 2, Census Tract 15.05, Mecklenburg County, North Carolina   
10   Block Group 3, Census Tract 15.07, Mecklenburg County, North Carolina   
11   Block Group 3, Census Tract 15.08, Mecklenburg County, North Carolina   
12   Block Group 1, Census Tract 15.10, Mecklenburg County, North Carolina   
13   Block Group 2, Census Tract 16.03, Mecklenburg County, North Carolina   
14   Block Group 2, Census Tract 16.06, Mecklenburg County, North Carolina   
15   Block Group 2, Census Tract 18.02, Mecklenburg County, North Carolina   
16   Block Group 3, Census Tract 19.10, Mecklenburg County, North Carolina   
17   Block Group 3, Census Tract 19.11, Mecklenburg County, North Carolina   
18   Block Group 1, Census Tract 19.16, Mecklenburg County, North Carolina   
19   Block Group 2, Census Tract 19.17, Mecklenburg County, North Carolina   
20   Block Group 3, Census Tract 19.18, Mecklenburg County, North Carolina   
21   Block Group 1, Census Tract 19.20, Mecklenburg County, North Carolina   
22   Block Group 1, Census Tract 19.21, Mecklenburg County, North Carolina   
23   Block Group 1, Census Tract 19.23, Mecklenburg County, North Carolina   
24   Block Group 1, Census Tract 19.25, Mecklenburg County, North Carolina   
25   Block Group 1, Census Tract 19.26, Mecklenburg County, North Carolina   
26   Block Group 2, Census Tract 19.27, Mecklenburg County, North Carolina   
27   Block Group 3, Census Tract 20.04, Mecklenburg County, North Carolina   
28   Block Group 1, Census Tract 20.06, Mecklenburg County, North Carolina   
29      Block Group 2, Census Tract 24, Mecklenburg County, North Carolina   
30      Block Group 2, Census Tract 25, Mecklenburg County, North Carolina   
31   Block Group 2, Census Tract 27.01, Mecklenburg County, North Carolina   
32   Block Group 2, Census Tract 27.02, Mecklenburg County, North Carolina   
33      Block Group 2, Census Tract 28, Mecklenburg County, North Carolina   
34   Block Group 2, Census Tract 29.03, Mecklenburg County, North Carolina   
35   Block Group 2, Census Tract 29.05, Mecklenburg County, North Carolina   
36   Block Group 1, Census Tract 29.08, Mecklenburg County, North Carolina   
37   Block Group 1, Census Tract 29.09, Mecklenburg County, North Carolina   
38   Block Group 3, Census Tract 29.10, Mecklenburg County, North Carolina   
39   Block Group 2, Census Tract 30.08, Mecklenburg County, North Carolina   
40   Block Group 2, Census Tract 30.12, Mecklenburg County, North Carolina   
41   Block Group 1, Census Tract 30.15, Mecklenburg County, North Carolina   
42   Block Group 2, Census Tract 30.22, Mecklenburg County, North Carolina   
43   Block Group 2, Census Tract 31.02, Mecklenburg County, North Carolina   
44   Block Group 2, Census Tract 31.05, Mecklenburg County, North Carolina   
45   Block Group 2, Census Tract 31.08, Mecklenburg County, North Carolina   
46   Block Group 1, Census Tract 31.10, Mecklenburg County, North Carolina   
47   Block Group 3, Census Tract 31.11, Mecklenburg County, North Carolina   
48   Block Group 1, Census Tract 32.03, Mecklenburg County, North Carolina   
49   Block Group 2, Census Tract 32.04, Mecklenburg County, North Carolina   
50   Block Group 2, Census Tract 33.01, Mecklenburg County, North Carolina   
51   Block Gro

In [7]:
len(Data)

624

### Rename columns with proper names

- Once we get our Data, use use the rename function in pandas to modify the column names for all the variables. 

In [8]:
Data.rename(columns={#########################################SEX BY AGE UNDER #######################################,
                       'B01001_003E':'Male_under_5E','B01001_003M':'Male_under_5M','B01001_004E':'Male_5_to_9E',
                       'B01001_004M':'Male_5_to_9M','B01001_005E':'Male_10_to_14E','B01001_005M':'Male_10_to_14M',
                       'B01001_006E':'Male_15_to_17E','B01001_006M':'Male_15_to_17M','B01001_027E':'Female_under_5E',
                       'B01001_027M':'Female_under_5M','B01001_028E':'Female_5_to_9E','B01001_028M':'Female_5_to_9M',
                       'B01001_029E':'Female_10_to_14E','B01001_029M':'Female_10_to_14M',
                       'B01001_030E':'Female_15_to_17E', 'B01001_030M':'Female_15_to_17M',
                       'B01001_001E':'Sex_By_Age_TotalE','B01001_001M':'Sex_By_Age_TotalM',
                    #######################################SEX BY AGE OVER#############################################,
                     'B01001_020E':'Male_65_to_66E','B01001_020M':'Male_65_to_66M','B01001_021E':'Male_67_to_69E',
                     'B01001_021M':'Male_67_to_69M','B01001_022E':'Male_70_to_74E','B01001_022M':'Male_70_to_74M',
                     'B01001_023E':'Male_75_to_79E','B01001_023M':'Male_75_to_79M','B01001_024E':'Male_80_to_84E',
                     'B01001_024M':'Male_80_to_84M','B01001_025E':'Male_85_and_overE','B01001_025M':'Male_85_and_overM',
                     'B01001_044E':'Female_65_to_66E','B01001_044M':'Female_65_to_66M','B01001_045E':'Female_67_to_69E',
                     'B01001_045M':'Female_67_to_69M','B01001_046E':'Female_70_to_74E','B01001_046M':'Female_70_to_74M',
                     'B01001_047E':'Female_75_to_79E','B01001_047M':'Female_75_to_79M','B01001_048E':'Female_80_to_84E',
                     'B01001_048M':'Female_80_to_84M','B01001_049E':'Female_85_and_overE',
                     'B01001_049M':'Female_85_and_overM',
                     ###################################### MEDIAN AGE ################################################,
                    'B01002_001E': 'Median_AgeE','B01002_001M':'Median_AgeM',
                     ############################## HISPANIC OR LATINO ORIGIN BY RACE ###############################,
                     'B03002_006E':'AsianAloneE','B03002_006M':'AsianAloneM','B03002_004E':'BlackAloneE',
                     'B03002_004M':'BlackAloneM','B03002_003E':'WhiteAloneE','B03002_003M':'WhiteAloneM',
                     'B03002_012E':'HispanicAloneE', 'B03002_012M':'HispanicAloneM','B03002_005E':'AmericanIndianAloneE',
                     'B03002_005M':'AmericanIndianAloneM','B03002_007E':'NativeHawaiianAloneE',
                     'B03002_007M':'NativeHawaiianAloneM','B03002_008E':'SomeOtherRaceAloneE',
                     'B03002_008M':'SomeOtherRaceAloneM','B03002_009E':'TwoorMoreRacesAloneE',
                     'B03002_009M':'TwoorMoreRacesAloneM','B03002_010E':'TwoorMoreRacesIncludingSomeotherRaceAloneE',
                     'B03002_010M':'TwoorMoreRacesIncludingSomeotherRaceAloneM',
                     'B03002_011E':'TwoorMoreRacesExcludingSomeotherRaceAloneE',
                     'B03002_011M':'TwoorMoreRacesExcludingSomeotherRaceAloneM','B03002_001E':'TotalRaceE', 
                     'B03002_001M':'TotalRaceM',
                     ############################### MEANS OF TRANSPORTATION TO WORK ##################################,
                     'B08134_021E':'DroveAloneE','B08134_021M':'DroveAloneM','B08134_001E':'TotalTransportationE',
                     'B08134_001M':'TotalTransportationM','B08134_015E':'Drove_20_to_24E','B08134_015M':'Drove_20_to_24M',
                     'B08134_016E':'Drove_25_to_29E','B08134_016M':'Drove_25_to_29M','B08134_017E':'Drove_30_to_34E',
                     'B08134_017M':'Drove_30_to_34M','B08134_018E':'Drove_35_to_44E','B08134_018M':'Drove_35_to_44M',
                     'B08134_019E':'Drove_45_to_59E','B08134_019M':'Drove_45_to_59M','B08134_020E':"Drove_60_or_MoreE", 
                     'B08134_020M':"Drove_60_or_MoreM",
                     #########################SEX BY ENROLLMENT BY LEVEL OF EDUCATION ##############################,
                     'B14002_009E':'Kindergaten_MaleE','B14002_009M':'Kindergaten_MaleM',
                     'B14002_012E':'Grade_1_to_4_MaleE','B14002_012M':'Grade_1_to_4_MaleM',
                     'B14002_015E':'Grade_5_to_8_MaleE','B14002_015M':'Grade_5_to_8_MaleM',
                     'B14002_018E':'Grade_9_to_12_MaleE','B14002_018M':'Grade_9_to_12_MaleM',
                     'B14002_033E':'Kindergaten_FemaleE', 'B14002_033M':'Kindergaten_FemaleM',
                     'B14002_036E':'Grade_1_to_4_FemaleE','B14002_036M':'Grade_1_to_4_FemaleM',
                     'B14002_039E':'Grade_5_to_8_FemaleE','B14002_039M':'Grade_5_to_8_FemaleM',
                     'B14002_042E':'Grade_9_to_12_FemaleE','B14002_042M':'Grade_9_to_12_FemaleM',
                     'B14002_007E':'Kindergaten_TotalMaleE','B14002_007M':'Kindergaten_TotalMaleM',
                     'B14002_010E':'Grade_1_to_4_TotalMaleE','B14002_010M':'Grade_1_to_4_TotalMaleM',
                     'B14002_013E':'Grade_5_to_8_TotalMaleE', 'B14002_013M':'Grade_5_to_8_TotalMaleM',
                     'B14002_016E':'Grade_9_to_12_TotalMaleE','B14002_016M':'Grade_9_to_12_TotalMaleM',
                     'B14002_031E':'Kindergaten_TotalFemaleE','B14002_031M':'Kindergaten_TotalFemaleM',
                     'B14002_034E':'Grade_1_to_4_TotalFemaleE','B14002_034M':'Grade_1_to_4_TotalFemaleM',
                     'B14002_037E':'Grade_5_to_8_TotalFemaleE','B14002_037M':'Grade_5_to_8_TotalFemaleM',
                     'B14002_040E':'Grade_9_to_12_TotalFemaleE' ,'B14002_040M':'Grade_9_to_12_TotalFemaleM',
                     ##################################EDUCATIONAL ATTAINMENT ############################,
                     'B15003_002E':'NoSchoolingE','B15003_002M':'NoSchoolingM','B15003_017E':'HighSchoolDiplomaE',
                     'B15003_017M':'HighSchoolDiplomaM','B15003_018E':'GEDorAlternativeE',
                     'B15003_018M':'GEDorAlternativeM','B15003_019E':'SomeCollegeLessThan1YearE',
                     'B15003_019M':'SomeCollegeLessThan1YearM','B15003_020E':'SomeCollege1orMoreYearsNoDegreeE',
                     'B15003_020M':'SomeCollege1orMoreYearsNoDegreeM',
                     'B15003_021E':'AssociateDegreeE','B15003_021M':'AssociateDegreeM','B15003_022E':'BachelorsDegreeE',
                     'B15003_022M':'BachelorsDegreeM','B15003_023E':'MastersDegreeE','B15003_023M':'MastersDegreeM',
                     'B15003_024E':'ProfessionalSchoolDegreeE','B15003_024M':'ProfessionalSchoolDegreeM',
                     'B15003_025E':'DoctorateDegreeE','B15003_025M':'DoctorateDegreeM',
                     'B15003_001E':'TotalEducationAttainmentE','B15003_001M':'TotalEducationAttainmentM',
                     ########################################MEDIAN HOUSEHOLDINCOME###################################,
                     'B19013_001E':'MedianHouseholdIncomeE','B19013_001M':'MedianHouseholdIncomeM',
                     ##########################SEX BY AGE BY VETERAN STATUS FOR CIVILIAN POPULATION#########################,
                     'B21001_002E':'VeteranE','B21001_002M':'VeteranM','B21001_001E':'TotalVeteranE',
                     'B21001_001M':'TotalVeteranM',
                     #############################EMPLOYMENT STATUS#################################,
                     'B23025_004E':'CivilianInLaborForceEmployedE','B23025_004M':'CivilianInLaborForceEmployedM',
                     'B23025_002E':'TotalInLaborForceE','B23025_002M':'TotalInLaborForceM',
                     ###########################OCCUPANCY STATUS##############################,
                     'B25002_003E':'VacantE','B25002_003M':'VacantM','B25002_001E':'TotalOccupancyE',
                     'B25002_001M':'TotalOccupancyM','B25002_002E':'OccupiedE','B25002_002M':'OccupiedM',
                     #########################TENURE BY VEHICLE AVAILABLE##########################################,
                     'B25044_010E':'RenterOccupiedNoVehicleE','B25044_010M':'RenterOccupiedNoVehicleM',
                     'B25044_003E':'OwnerOccupiedNoVehicleE','B25044_003M':'OwnerOccupiedNoVehicleM',
                     'B25044_001E':'TotalVehicleByTenureE','B25044_001M':'TotalVehicleByTenureM',
                     ########################GROSS RENT ####################################,
                     'B25063_001E':'TotalGrossRentE','B25063_001M':'TotalGrossRentM',
                     ###################################Owneroccupied####################################
                     'B25003_002E':'OwnerOccupiedE', 'B25003_002M':'OwnerOccupiedM',
                     'B25003_001E':'TotalOwnerOccupiedE', 'B25003_001M':'TotalOwnerOccupiedM',
                     ############################## Internet ##############################################
                     'B28011_004E': 'BroadbandE', 'B28011_004M':'BroadbandM', 'B28011_001E':'TotalBroadbandE'
                     ,'B28011_001M': 'TotalBroadbandM'
                    
                    },
           inplace = True)



#### Convert variables to integer 

- The output of our data from the API is pandas object(string), so we cannot perform mathematical operations on them. Hence we convert the numerical variables to integer 

In [9]:
col = []

for row in Data.columns:
    if row not in ('NAME','GEO_ID','state','county','tract','block group'):
        col.append(row)
        
        
for row in col:
    Data[row]= Data[row].apply(np.int64)
    
# print(Data.dtypes)
    

#### Replace Null Values with NA

- Data from the census API which are NaN values shows either as -666666666.0, -222222222.0, or -333333333.0, we search and replace all of them with actual NaNs values using numpy

In [10]:
Data.replace(-666666666.0,np.nan,inplace= True)
Data.replace(-222222222.0,np.nan,inplace= True)
Data.replace(-333333333.0,np.nan,inplace= True)

In [11]:
# Data.dtypes

#### Calculate Margin of Error

- To compute the margin of error, we first square all the Margin of error
- We target any variable that ends with capital 'M' and square it. In subsequent steps, we will use suffix and prefix to identify sets of variables, here we identify Margin of errors with 'M'

In [12]:
for row in Data:
    if row.endswith("M"):
        Data[str(row)] = Data[str(row)]**2

#### Derived Margin of Error

- The first step in calculating the derived margin of error is to sum  the individual squared margin of error of each derived measure. For example, if we want derived margin of error for individuals under 18, we have to sum the squared margin of error for males and females who are under the age of 18



- For variables which have multiple zero estimates, we are only interested in the first margin or error. We skip everyother margin of error with zero estimates. To do this, we count the number of variables with zero estimates, and sum the count. 




- For variables where the sum of count of zero estimates is zero, we keep the sum of the derived margin of error. For those where the sum of count of zero estimates is not zero, we multiple the count by 144 and subtract it from the sum of the margin of error, then add 144.  

##### Under 18  MOE

In [13]:
Under18MOE = ['Male_under_5M', 'Male_5_to_9M', 'Male_10_to_14M', 'Male_15_to_17M',
              'Female_under_5M', 'Female_5_to_9M', 'Female_10_to_14M', 'Female_15_to_17M']

Under18E = ['Male_under_5E', 'Male_5_to_9E', 'Male_10_to_14E', 'Male_15_to_17E',
              'Female_under_5E', 'Female_5_to_9E', 'Female_10_to_14E', 'Female_15_to_17E']


Data['Under18MOEZero'] = (Data[Under18E]==0).sum(1)
Data['Under18MOENonZero'] = Data[Under18MOE].sum(1)
Data['Under18MOEN'] = np.where(Data['Under18MOEZero']== 0, Data['Under18MOENonZero'],
                               (Data['Under18MOENonZero']-Data['Under18MOEZero']*144)+144)

Data['SexbyAgeMOED'] = Data['Sex_By_Age_TotalM']

##### Over 65 MOE

In [14]:
Over65MOE = ['Male_65_to_66M', 'Male_67_to_69M', 'Male_70_to_74M', 'Male_75_to_79M', 'Male_80_to_84M',
             'Male_85_and_overM', 'Female_65_to_66M', 'Female_67_to_69M', 'Female_70_to_74M', 'Female_75_to_79M',
             'Female_80_to_84M', 'Female_85_and_overM']


Over65E = ['Male_65_to_66E', 'Male_67_to_69E', 'Male_70_to_74E', 'Male_75_to_79E', 'Male_80_to_84E',
             'Male_85_and_overE', 'Female_65_to_66E', 'Female_67_to_69E', 'Female_70_to_74E', 'Female_75_to_79E',
             'Female_80_to_84E', 'Female_85_and_overE']



Data['Over65MOEZero'] =(Data[Over65E]==0).sum(1)
Data['Over65MOENonZero'] = Data[Over65MOE].sum(1)
Data['Over65MOEN'] = np.where(Data['Over65MOEZero']== 0, Data['Over65MOENonZero'],
                              (Data['Over65MOENonZero']-Data['Over65MOEZero']*144)+144)

 


##### Race MOE

In [15]:
RaceOtherMOE = ['AmericanIndianAloneM','NativeHawaiianAloneM','SomeOtherRaceAloneM','TwoorMoreRacesAloneM'] #Incuding/Excluding

RaceOtherE = ['AmericanIndianAloneE','NativeHawaiianAloneE','SomeOtherRaceAloneE','TwoorMoreRacesAloneE']


Data['AsianMOEN'] = Data['AsianAloneM']
Data['BlackMOEN'] = Data['BlackAloneM']
Data['WhiteMOEN'] = Data['WhiteAloneM']
Data['HispanicMOEN'] = Data['HispanicAloneM']

Data['OtherMOEZero'] =  (Data[RaceOtherE]==0).sum(1)
Data['OtherMOENonZero'] = Data[RaceOtherMOE].sum(1)
Data['OtherMOEN'] = np.where(Data['OtherMOEZero']== 0,  Data['OtherMOENonZero'],
                              (Data['OtherMOENonZero']-Data['OtherMOEZero']*144)+144)


Data['TotalRaceMOED'] = Data['TotalRaceM']


##### Commute Alone MOE

In [16]:
CommuteMOE = ['Drove_20_to_24M', 'Drove_25_to_29M', 'Drove_30_to_34M', 'Drove_35_to_44M', 
                 'Drove_45_to_59M', 'Drove_60_or_MoreM']

CommuteE = ['Drove_20_to_24E', 'Drove_25_to_29E', 'Drove_30_to_34E', 'Drove_35_to_44E', 
                 'Drove_45_to_59E', 'Drove_60_or_MoreE']


Data['DroveMOEZero'] = (Data[CommuteE]==0).sum(1)
Data['DroveMOENonZero'] = Data[CommuteMOE].sum(1)
Data['DroveMoreThan20MinutesMOEN'] = np.where(Data['DroveMOEZero']== 0, Data['DroveMOENonZero'],
                              (Data['DroveMOENonZero']-Data['DroveMOEZero'] *144)+144)



Data['TotalTransportationMOED'] = Data['TotalTransportationM']

##### Private (No School or Pre School) MOE

In [17]:
PrivateMOE = ['Kindergaten_MaleM','Grade_1_to_4_MaleM','Grade_5_to_8_MaleM','Grade_9_to_12_MaleM',
          'Kindergaten_FemaleM','Grade_1_to_4_FemaleM','Grade_5_to_8_FemaleM','Grade_9_to_12_FemaleM']

PrivateE = ['Kindergaten_MaleE','Grade_1_to_4_MaleE','Grade_5_to_8_MaleE','Grade_9_to_12_MaleE',
          'Kindergaten_FemaleE','Grade_1_to_4_FemaleE','Grade_5_to_8_FemaleE','Grade_9_to_12_FemaleE']


Data['PrivateNoSchoolMOEZero'] =   (Data[PrivateE ]==0).sum(1)
Data['PrivateNoSchoolMOENonZero'] =  Data[PrivateMOE].sum(1)
Data['PrivateNoSchoolMOEN'] = np.where(Data['PrivateNoSchoolMOEZero']== 0,Data['PrivateNoSchoolMOENonZero'],
                              (Data['PrivateNoSchoolMOENonZero'] - Data['PrivateNoSchoolMOEZero'] *144)+144)
##############################################################################################################


PrivateTotalMOE = ['Kindergaten_TotalMaleM','Grade_1_to_4_TotalMaleM','Grade_5_to_8_TotalMaleM',
               'Grade_9_to_12_TotalMaleM','Kindergaten_TotalFemaleM','Grade_1_to_4_TotalFemaleM',
               'Grade_5_to_8_TotalFemaleM','Grade_9_to_12_TotalFemaleM' ]

PrivateTotalE = ['Kindergaten_TotalMaleE','Grade_1_to_4_TotalMaleE','Grade_5_to_8_TotalMaleE',
               'Grade_9_to_12_TotalMaleE','Kindergaten_TotalFemaleE','Grade_1_to_4_TotalFemaleE',
               'Grade_5_to_8_TotalFemaleE','Grade_9_to_12_TotalFemaleE' ]


Data['PrivateNoSchoolTotalMOEDZero'] =  (Data[PrivateTotalE]==0).sum(1)
Data['PrivateNoSchoolTotalMOEDNonZero'] =  Data[PrivateTotalMOE].sum(1)
Data['PrivateNoSchoolTotalMOED'] = np.where(Data['PrivateNoSchoolTotalMOEDZero']== 0, Data['PrivateNoSchoolTotalMOEDNonZero'],
                              (Data['PrivateNoSchoolTotalMOEDNonZero'] - Data['PrivateNoSchoolTotalMOEDZero'] *144)+144)


##### Adults With High School Diploma MOE

In [18]:
HighschoolMOE = ['HighSchoolDiplomaM','GEDorAlternativeM','SomeCollegeLessThan1YearM',
              'SomeCollege1orMoreYearsNoDegreeM','AssociateDegreeM','BachelorsDegreeM',
             'MastersDegreeM','ProfessionalSchoolDegreeM','DoctorateDegreeM']



HighschoolE = ['HighSchoolDiplomaE','GEDorAlternativeE','SomeCollegeLessThan1YearE',
              'SomeCollege1orMoreYearsNoDegreeE','AssociateDegreeE','BachelorsDegreeE',
             'MastersDegreeE','ProfessionalSchoolDegreeE','DoctorateDegreeE']                        #Takeout Noschooling?

Data['HighSchoolDiplomaMOEZero'] = (Data[HighschoolE]==0).sum(1)
Data['HighSchoolDiplomaMOENonZero'] = Data[HighschoolMOE].sum(1)
Data['HighSchoolDiplomaMOEN'] = np.where(Data['HighSchoolDiplomaMOEZero']== 0, Data['HighSchoolDiplomaMOENonZero'],
                              (Data['HighSchoolDiplomaMOENonZero']-Data['HighSchoolDiplomaMOEZero']*144)+144)
                                                                        
Data['TotalEducationAttainmentMOED'] = Data['TotalEducationAttainmentM']


##### Adults with At Least Bachelors Degrees MOE

In [19]:
BachelorsMOE = ['BachelorsDegreeM','MastersDegreeM','ProfessionalSchoolDegreeM','DoctorateDegreeM']
BachelorsE = ['BachelorsDegreeE','MastersDegreeE','ProfessionalSchoolDegreeE','DoctorateDegreeE']


Data['AdultsWithAtLeastBachelorsMOEZero'] = (Data[BachelorsE ]==0).sum(1)
Data['AdultsWithAtLeastBachelorsMOENonZero'] = Data[BachelorsMOE].sum(1)
Data['AdultsWithAtLeastBachelorsMOEN'] = np.where(Data['AdultsWithAtLeastBachelorsMOEZero']== 0, 
                                                  Data['AdultsWithAtLeastBachelorsMOENonZero'],
                                                  ( Data['AdultsWithAtLeastBachelorsMOENonZero']-
                                                   Data['AdultsWithAtLeastBachelorsMOEZero'] *144)+144)
                                      

Data['TotalEducationAttainmentMOED'] = Data['TotalEducationAttainmentM']

#### Drove Alone 

In [20]:
Data['DroveAloneMOEN'] = Data['DroveAloneM']
Data['TotalTransportationMOED'] = Data['TotalTransportationM']

##### Veteran MOE

In [21]:
Data['VeteranMOEN'] = Data['VeteranM']
Data['TotalVeteranMOED'] = Data['TotalVeteranM']

##### Unemployment MOE

In [22]:
Data['EmployedMOEN'] = Data['CivilianInLaborForceEmployedM']
Data['TotalInLaborForceMOED'] = Data['TotalInLaborForceM']

##### Vacancy  MOE

In [23]:
Data['VacantMOEN'] = Data['VacantM']
Data['TotalOccupancyMOED'] = Data['TotalOccupancyM']

#####  Occupied  MOE

In [24]:
Data['OccupiedMOEN'] = Data['OccupiedM']
Data['TotalOccupancyMOED'] = Data['TotalOccupancyM']

#### Owner Occupied

In [25]:
Data['OwnerOccupiedMOEN'] = Data['OwnerOccupiedM']
Data['TotalOwnerOccupiedMOED'] = Data['TotalOwnerOccupiedM']

#### Internet Access

In [26]:
Data['BroadbandMOEN'] = Data['BroadbandM']
Data['TotalBroadbandMOED'] = Data['TotalBroadbandM']

#### Gross Rent

In [27]:
# Data['GrossRentMOEN'] = Data['TotalGrossRentM']

#### Median Household Income

In [28]:
# Data['MedianHouseholdIncomeMOEN'] = Data['MedianHouseholdIncomeM']

#### Median Age

In [29]:
# Data['MedianAgeMOEN'] = Data['Median_AgeM']

###### No Vehicle MOE

In [30]:
NoVehicleMOE = ['RenterOccupiedNoVehicleM','OwnerOccupiedNoVehicleM']
NoVehicleE = ['RenterOccupiedNoVehicleE','OwnerOccupiedNoVehicleE']

Data['NoVehicleMOEZero'] =(Data[NoVehicleE]==0).sum(1)
Data['NoVehicleMOENonZero'] = Data[NoVehicleMOE].sum(1)
Data['NoVehicleMOEN'] = np.where(Data['NoVehicleMOEZero']== 0, Data['NoVehicleMOENonZero'],
                              (Data['NoVehicleMOENonZero']-Data['NoVehicleMOEZero']*144)+144)
                                                                      
                   
Data['TotalVehicleByTenureMOED'] = Data['TotalVehicleByTenureM']

#### Join BlockGroup Data to NPA data 

- After calculating the derived margins of error, we join the output to NPA data using GEOID

- To create GEOID from the ACS Data, we combine the state ID, the County ID, the Census Tract ID and the Block Group ID, and use astype to makesure the data type is an integer since the NPA GEOID2 is an integer data type


In [22]:
Data['GEOID'] = (Data['state'] + Data['county'] + Data['tract'] + Data['block group']).astype('int64')

- Read NPA Crosswalkdata. This is on github that is why it is a weblink 

In [23]:
# NPA = pd.read_csv('https://raw.githubusercontent.com/MLProject20/Data/main/NPA_Census_Crosswalk.csv')
# NPA

In [24]:
NPA = pd.read_csv('https://raw.githubusercontent.com/MLProject20/Data/main/NPA_Census_Crosswalk_2020.csv')

In [37]:
NPA

GEOID2       NAMELSAD  NPA
0    371190015082  Block Group 2  325
1    371190056151  Block Group 1  296
2    371190038081  Block Group 1   79
3    371190015091  Block Group 1  271
4    371190015101  Block Group 1   17
5    371190062122  Block Group 2  416
6    371190062102  Block Group 2  421
7    371190055133  Block Group 3  252
8    371190055223  Block Group 3  274
9    371190055113  Block Group 3  279
10   371190055101  Block Group 1  280
11   371190055111  Block Group 1  281
12   371190039031  Block Group 1  306
13   371199802001  Block Group 1  285
14   371190058481  Block Group 1  380
15   371190030121  Block Group 1  236
16   371190055081  Block Group 1   38
17   371190058302  Block Group 2  261
18   371190019181  Block Group 1   16
19   371190058461  Block Group 1  379
20   371190058161  Block Group 1  262
21   371190056191  Block Group 1  360
22   371190019113  Block Group 3   91
23   371190015043  Block Group 3  327
24   371190040002  Block Group 2  124
25   371190058171  Block Group 1   29
26   371190055102  Block Group 2  117
27   371190058462  Block Group 2  379
28   371190019211  Block Group 1  186
29   371190044002  Block Group 2  158
30   371190030131  Block Group 1  201
31   371190057101  Block Group 1  442
32   371190042003  Block Group 3    6
33   371190030081  Block Group 1  177
34   371190058473  Block Group 3  149
35   371190054032  Block Group 2  150
36   371199803001  Block Group 1  476
37   371190058292  Block Group 2  298
38   371190056122  Block Group 2  299
39   371190058271  Block Group 1  142
40   371190019202  Block Group 2  180
41   371190059151  Block Group 1   92
42   371190059161  Block Group 1   93
43   371190059162  Block Group 2   94
44   371190064032  Block Group 2  468
45   371190016082  Block Group 2  168
46   371190058362  Block Group 2  443
47   371190058361  Block Group 1  444
48   371190058282  Block Group 2  297
49   371190058291  Block Group 1  300
50   371190030122  Block Group 2  302
51   371190030082  Block Group 2  303
52   371190053082  Block Group 2  304
53   371190061031  Block Group 1  109
54   371190058482  Block Group 2  380
55   371190058472  Block Group 2  148
56   371190055192  Block Group 2  195
57   371190019172  Block Group 2  220
58   371190058432  Block Group 2  204
59   371190058333  Block Group 3  456
60   371190057151  Block Group 1  396
61   371190058301  Block Group 1   41
62   371190064041  Block Group 1  469
63   371190031081  Block Group 1   12
64   371190031062  Block Group 2  105
65   371190031023  Block Group 3  106
66   371190060092  Block Group 2  332
67   371190062092  Block Group 2  397
68   371190021002  Block Group 2  394
69   371190058431  Block Group 1  170
70   371190058162  Block Group 2  171
71   371190058452  Block Group 2  172
72   371190057161  Block Group 1  131
73   371190019203  Block Group 3  134
74   371190058331  Block Group 1  457
75   371190030163  Block Group 3  206
76   371190030171  Block Group 1  351
77   371190056213  Block Group 3  225
78   371190032031  Block Group 1   13
79   371190032032  Block Group 2  226
80   371190043042  Block Group 2  173
81   371190062142  Block Group 2  445
82   371190062141  Block Group 1  446
83   371190027021  Block Group 1  392
84   371190032041  Block Group 1  357
85   371190032042  Block Group 2  357
86   371190056212  Block Group 2  228
87   371190062091  Block Group 1  398
88   371190062093  Block Group 3  399
89   371190056102  Block Group 2   46
90   371190056091  Block Group 1   60
91   371190056101  Block Group 1   61
92   371190056042  Block Group 2   62
93   371190029051  Block Group 1  208
94   371190029033  Block Group 3  210
95   371190055151  Block Group 1  372
96   371190038071  Block Group 1  212
97   371190055172  Block Group 2  372
98   371190055171  Block Group 1  372
99   371190055191  Block Group 1  372
100  371190056111  Block Group 1  155
101  371190057131  Block Group 1  403
102  371190030152  Block Group 2  175
103  371190058151  Block Group 1  181
104  371199801001  Bl

In [26]:
#Check if all GEOIDs are present

a = list(Data['GEOID'])
b = list(NPA['GEOID2'])
unmatch = list(set(a).difference(b))
len(unmatch)

0

##### Join Data using the common field GEOID

In [27]:
NPAData = pd.merge(NPA,Data, how = "left", left_on = ['GEOID2'], right_on= ['GEOID'])

In [28]:
len(NPAData)

624

In [37]:
Data = NPAData.groupby('NPA').sum()

#### Derived Estimates and MOE

- This steps aggregate estimates for derived proportions and also calculate the margin of error for each derived proportion 

- We used the aggregated estimates to create derived proportions

- We then aggregate the numerator and the denominator margin of error for each of the derived proportions (We are supposed to square before we aggregate but we have already done that in the step aboved when we were calculating the Margin of error for the estimates)



##### Under 18

In [38]:
Under18E = ['Male_under_5E', 'Male_5_to_9E', 'Male_10_to_14E', 'Male_15_to_17E',
              'Female_under_5E', 'Female_5_to_9E', 'Female_10_to_14E', 'Female_15_to_17E']


Data['Under18A'] = Data[Under18E].sum(1)

In [39]:
Under18M = ['Male_under_5M', 'Male_5_to_9M', 'Male_10_to_14M', 'Male_15_to_17M',
              'Female_under_5M', 'Female_5_to_9M', 'Female_10_to_14M', 'Female_15_to_17M']

Data['Under18NMO'] = Data[Under18M].sum(1)

Data['SexbyAgeDMO'] = Data['Sex_By_Age_TotalM']

##### Over 65

In [40]:
Over65E = ['Male_65_to_66E', 'Male_67_to_69E', 'Male_70_to_74E', 'Male_75_to_79E', 'Male_80_to_84E',
             'Male_85_and_overE', 'Female_65_to_66E', 'Female_67_to_69E', 'Female_70_to_74E', 'Female_75_to_79E',
             'Female_80_to_84E', 'Female_85_and_overE']

Data['Over65A'] = Data[Over65E].sum(1)

In [41]:
Over65M = ['Male_65_to_66M', 'Male_67_to_69M', 'Male_70_to_74M', 'Male_75_to_79M', 'Male_80_to_84M',
             'Male_85_and_overM', 'Female_65_to_66M', 'Female_67_to_69M', 'Female_70_to_74M', 'Female_75_to_79M',
             'Female_80_to_84M', 'Female_85_and_overM']

Data['Over65NMO'] = Data[Over65M].sum(1)


##### Race

In [42]:
RaceOtherE = ['AmericanIndianAloneE','NativeHawaiianAloneE','SomeOtherRaceAloneE','TwoorMoreRacesAloneE']

Data['RaceOtherA'] = Data[RaceOtherE].sum(1)

In [43]:
RaceOtherM = ['AmericanIndianAloneM','NativeHawaiianAloneM','SomeOtherRaceAloneM','TwoorMoreRacesAloneM']

Data['RaceOtherNMO'] = Data[RaceOtherM].sum(1)

Data['TotalRaceDMO'] = Data['TotalRaceM']

Data['AsianAloneNMO'] = Data['AsianAloneM']
Data['BlackAloneNMO'] = Data['BlackAloneM']
Data['WhiteAloneNMO'] = Data['WhiteAloneM']
Data['HispanicAloneNMO'] = Data['HispanicAloneM']

##### Commute Alone

In [44]:
CommuteE = ['Drove_20_to_24E', 'Drove_25_to_29E', 'Drove_30_to_34E', 'Drove_35_to_44E', 
                 'Drove_45_to_59E', 'Drove_60_or_MoreE']

Data['DriveMoreThan20MinutesA'] = Data[CommuteE].sum(1)



In [45]:
CommuteM = ['Drove_20_to_24M', 'Drove_25_to_29M', 'Drove_30_to_34M', 'Drove_35_to_44M', 
                 'Drove_45_to_59M', 'Drove_60_or_MoreM']

Data['DriveMoreThan20MinutesNMO'] = Data[CommuteM].sum(1)

Data['TotalTransportationDMO'] = Data['TotalTransportationM']

##### Percent Private (No School or Pre School)

In [46]:
PrivateE = ['Kindergaten_MaleE','Grade_1_to_4_MaleE','Grade_5_to_8_MaleE','Grade_9_to_12_MaleE',
          'Kindergaten_FemaleE','Grade_1_to_4_FemaleE','Grade_5_to_8_FemaleE','Grade_9_to_12_FemaleE']


PrivateTotalE = ['Kindergaten_TotalMaleE','Grade_1_to_4_TotalMaleE','Grade_5_to_8_TotalMaleE',
               'Grade_9_to_12_TotalMaleE','Kindergaten_TotalFemaleE','Grade_1_to_4_TotalFemaleE',
               'Grade_5_to_8_TotalFemaleE','Grade_9_to_12_TotalFemaleE' ]

Data['PrivateA'] = Data[PrivateE].sum(1)

Data['PrivateTotalA'] = Data[PrivateTotalE].sum(1)

In [47]:
PrivateM = ['Kindergaten_MaleM','Grade_1_to_4_MaleM','Grade_5_to_8_MaleM','Grade_9_to_12_MaleM',
          'Kindergaten_FemaleM','Grade_1_to_4_FemaleM','Grade_5_to_8_FemaleM','Grade_9_to_12_FemaleM']


PrivateTotalM = ['Kindergaten_TotalMaleM','Grade_1_to_4_TotalMaleM','Grade_5_to_8_TotalMaleM',
               'Grade_9_to_12_TotalMaleM','Kindergaten_TotalFemaleM','Grade_1_to_4_TotalFemaleM',
               'Grade_5_to_8_TotalFemaleM','Grade_9_to_12_TotalFemaleM' ]

Data['PrivateNMO'] = Data[PrivateM].sum(1)

Data['PrivateTotalDMO'] = Data[PrivateTotalM].sum(1)

##### Adults With High School Diploma

In [48]:
HighschoolE = ['HighSchoolDiplomaE','GEDorAlternativeE','SomeCollegeLessThan1YearE',
              'SomeCollege1orMoreYearsNoDegreeE','AssociateDegreeE','BachelorsDegreeE',
             'MastersDegreeE','ProfessionalSchoolDegreeE','DoctorateDegreeE']  


Data['HighSchoolDiplomaA'] = Data[HighschoolE].sum(1)

In [49]:
HighschoolM = ['HighSchoolDiplomaM','GEDorAlternativeM','SomeCollegeLessThan1YearM',
              'SomeCollege1orMoreYearsNoDegreeM','AssociateDegreeM','BachelorsDegreeM',
             'MastersDegreeM','ProfessionalSchoolDegreeM','DoctorateDegreeM']  


Data['HighSchoolDiplomaNMO'] = Data[HighschoolM].sum(1)

Data['TotalEducationAttainmentDMO'] = Data['TotalEducationAttainmentM']


##### Adults with At Least Bachelors Degrees

In [50]:
BachelorsE = ['BachelorsDegreeE','MastersDegreeE','ProfessionalSchoolDegreeE','DoctorateDegreeE']


Data['AdultsWithAtLeastBachelorsA'] = Data[BachelorsE].sum(1)

In [51]:
BachelorsM = ['BachelorsDegreeM','MastersDegreeM','ProfessionalSchoolDegreeM','DoctorateDegreeM']


Data['AdultsWithAtLeastBachelorsNMO'] = Data[BachelorsM].sum(1)

Data['TotalEducationAttainmentDMO'] = Data['TotalEducationAttainmentM']

###### No Vehicle

In [52]:
NoVehicleE = ['RenterOccupiedNoVehicleE','OwnerOccupiedNoVehicleE']

Data['NoVehicleA'] = Data[NoVehicleE].sum(1)

In [53]:
NoVehicleM = ['RenterOccupiedNoVehicleM','OwnerOccupiedNoVehicleM']

Data['NoVehicleNMO'] = Data[NoVehicleM].sum(1)

Data['TotalVehicleByTenureDMO'] = Data['TotalVehicleByTenureM']

#### Drove Alone

In [54]:
Data['DroveAloneNMO'] = Data['DroveAloneM']
Data['TotalTransportationDMO'] = Data['TotalTransportationM']

#### Veteran

In [55]:
Data['VeteranNMO'] = Data['VeteranM']
Data['TotalVeteranDMO'] = Data['TotalVeteranM']

#### Unemployment 

In [56]:
Data['EmployedNMO'] = Data['CivilianInLaborForceEmployedM']
Data['TotalInLaborForceDMO'] = Data['TotalInLaborForceM']

#### Internet Access

In [57]:
Data['BroadbandNMO'] = Data['BroadbandM']
Data['TotalBroadbandDMO'] = Data['TotalBroadbandM']

#### Vacancy 

In [58]:
Data['VacantNMO'] = Data['VacantM']
Data['TotalOccupancyDMO'] = Data['TotalOccupancyM']

#### Occupied

In [59]:
Data['OccupiedNMO'] = Data['OccupiedM']
Data['TotalOccupancyDMO'] = Data['TotalOccupancyM']

#### OwnerOccupied

In [60]:
Data['OwnerOccupiedNMO'] = Data['OwnerOccupiedM']
Data['TotalOwnerOccupiedDMO'] = Data['TotalOwnerOccupiedM']

### Derived Proportions

- To create the derived proportion, we divide the aggregated estimates by the total estimates 

#### Under 18

In [61]:
Data['PercentUnder18'] =  (Data['Under18A']/Data['Sex_By_Age_TotalE'])

#### Over65

In [62]:
 Data['PercentOver65'] = (Data['Over65A']/Data['Sex_By_Age_TotalE'])

#### Race 

In [63]:
Data['PercentAsian'] = (Data['AsianAloneE']/Data['TotalRaceE'])
Data['PercentBlack'] = (Data['BlackAloneE']/Data['TotalRaceE'])
Data['PercentWhite'] = (Data['WhiteAloneE']/Data['TotalRaceE'])
Data['PercentHispanic'] = (Data['HispanicAloneE']/Data['TotalRaceE'])
Data['PercentOther'] = (Data['RaceOtherA']/Data['TotalRaceE'])

#### Commute

In [64]:
Data['PercentDroveMoreThan20Minutes'] = (Data['DriveMoreThan20MinutesA']/Data['TotalTransportationE'])

#### Highschool Diploma

In [65]:
Data['PercentHighSchoolDiploma'] = (Data['HighSchoolDiplomaA']/Data['TotalEducationAttainmentE'])

#### Bachelors

In [66]:
Data['PercentAdultsWithAtLeastBachelors'] = (Data['AdultsWithAtLeastBachelorsA']/Data['TotalEducationAttainmentE'])

#### Private (No School or Pre School)

In [67]:
Data['PercentPrivateSchool'] = Data['PrivateA']/Data['PrivateTotalA']    ## Not Percent but for consistency

#### Drove Alone

In [68]:
Data['PercentDroveAlone'] = Data['DroveAloneE']/Data['TotalTransportationE']

#### Veterans

In [69]:
Data['PercentVeteran'] = (Data['VeteranE']/Data['TotalVeteranE'])

#### Employment Status

In [70]:
 Data['PercentEmployed'] = (Data['CivilianInLaborForceEmployedE']/Data['TotalInLaborForceE'])

#### Internet Access

In [71]:
Data['PercentInternetAccess'] = Data['BroadbandE']/Data['TotalBroadbandE']

#### Vacant 

In [72]:
Data['PercentVacant'] = (Data['VacantE']/Data['TotalOccupancyE'])

#### Occupied

In [73]:
Data['PercentOccupied'] = (Data['OccupiedE']/Data['TotalOccupancyE'])

#### Owner Occupied

In [74]:
Data['PercentOwnerOccupied'] = Data['OwnerOccupiedE']/Data['TotalOwnerOccupiedE']

#### No Vehicle

In [75]:
Data['PercentNoVehicle'] = (Data['NoVehicleA']/Data['TotalVehicleByTenureE'])

### Square the percentages (Derived Proportion)

- The next step to calculate the margin of error for our derived proportion is squaring our derived proportion 

In [76]:
for row in Data: 
    if row.startswith('Per'):
        Data[str(row)+'PS'] = Data[str(row)]**2

### Square MOE numerator and denominator

- We then square the numerator of the margins of error

In [77]:
#For numerator

for row in Data:
    if row.endswith("NMO"):
        print(row)

Under18NMO
Over65NMO
RaceOtherNMO
AsianAloneNMO
BlackAloneNMO
WhiteAloneNMO
HispanicAloneNMO
DriveMoreThan20MinutesNMO
PrivateNMO
HighSchoolDiplomaNMO
AdultsWithAtLeastBachelorsNMO
NoVehicleNMO
DroveAloneNMO
VeteranNMO
EmployedNMO
BroadbandNMO
VacantNMO
OccupiedNMO
OwnerOccupiedNMO


In [78]:
#For denominator

for row in Data:
    if row.endswith("DMO"):
        print(row)

SexbyAgeDMO
TotalRaceDMO
TotalTransportationDMO
PrivateTotalDMO
TotalEducationAttainmentDMO
TotalVehicleByTenureDMO
TotalVeteranDMO
TotalInLaborForceDMO
TotalBroadbandDMO
TotalOccupancyDMO
TotalOwnerOccupiedDMO


#### Derived Proportion MOE

- Following the formula below, we calculate the margin of error for derived proportions

<img src="https://github.com/MLProject20/Data/blob/main/MOE.PNG?raw=true" width=300 height = 100/>


 [Formula For Calculating MOE For Derived Proportion](https://github.com/MLProject20/Data/blob/main/MOE.PNG?raw=true 'Margin of Error for Derived Estimates')



#### Under 18 Derived Proportion MOE

In [79]:
Data['Under18DerivedMOEP'] = (np.sqrt(Data['Under18NMO'] -
                                      (Data['PercentUnder18PS']*Data['SexbyAgeDMO']))/Data['Sex_By_Age_TotalE'])

C:\Users\padu\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone-2\lib\site-packages\pandas\core\arraylike.py:364: RuntimeWarning: invalid value encountered in sqrt
  result = getattr(ufunc, method)(*inputs, **kwargs)


In [80]:
Data['Under18DerivedMOEPR'] = np.where(np.isnan(Data['Under18DerivedMOEP'])!= True,Data['Under18DerivedMOEP'],
                              (np.sqrt(Data['Under18NMO'] +
                                      (Data['PercentUnder18PS']*Data['SexbyAgeDMO']))/Data['Sex_By_Age_TotalE']))

In [81]:
np.where(np.isnan(Data['Under18DerivedMOEP']))

(array([ 25,  50,  68, 115, 118, 130, 149, 168, 195, 262, 279, 311, 330,
        340], dtype=int64),)

In [82]:
np.where(np.isnan(Data['Under18DerivedMOEPR']))

(array([118, 279], dtype=int64),)

#### Over65 Derived Proportion MOE

In [83]:
Data['Over65DerivedMOEP'] = (np.sqrt(Data['Over65NMO'] -
                                     (Data['PercentOver65PS']*Data['SexbyAgeDMO']))/Data['Sex_By_Age_TotalE'])

In [84]:
Data['Over65DerivedMOEPR'] = np.where(np.isnan(Data['Over65DerivedMOEP'])!= True,Data['Over65DerivedMOEP'],
                             (np.sqrt(Data['Over65NMO'] +
                                     (Data['PercentOver65PS']*Data['SexbyAgeDMO']))/Data['Sex_By_Age_TotalE']))
                                    

In [85]:
np.where(np.isnan(Data['Over65DerivedMOEP'])) 

(array([ 24,  38,  97, 114, 118, 173, 279, 312, 385, 439], dtype=int64),)

In [86]:
np.where(np.isnan(Data['Over65DerivedMOEPR'])) 

(array([118, 279], dtype=int64),)

#### Race Derived Proportion MOE

In [87]:
Data['RaceOtherDerivedMOEP'] = (np.sqrt(Data['RaceOtherNMO']-
                                (Data['PercentOtherPS']*Data['TotalRaceDMO']))/Data['TotalRaceE'])



Data['RaceOtherDerivedMOEPR'] = np.where(np.isnan(Data['RaceOtherDerivedMOEP'])!= True,Data['RaceOtherDerivedMOEP'],
                              (np.sqrt(Data['RaceOtherNMO']+
                                (Data['PercentOtherPS']*Data['TotalRaceDMO']))/Data['TotalRaceE']))      

#**************************************************************


Data['AsianDerivedMOEP'] = (np.sqrt(Data['AsianAloneNMO']- 
                            (Data['PercentOtherPS']*Data['TotalRaceDMO']))/Data['TotalRaceE'])



Data['AsianDerivedMOEPR'] = np.where(np.isnan(Data['AsianDerivedMOEP'])!= True,Data['AsianDerivedMOEP'],
                             (np.sqrt(Data['AsianAloneNMO']+ 
                            (Data['PercentOtherPS']*Data['TotalRaceDMO']))/Data['TotalRaceE']))    

#**************************************************************
                                         
Data['BlackAloneDerivedMOEP'] = (np.sqrt(Data['BlackAloneNMO']- 
                                 (Data['PercentOtherPS']*Data['TotalRaceDMO']))/Data['TotalRaceE'])


Data['BlackAloneDerivedMOEPR'] = np.where(np.isnan(Data['BlackAloneDerivedMOEP'])!= True,Data['BlackAloneDerivedMOEP'],
                            (np.sqrt(Data['BlackAloneNMO']+ 
                                 (Data['PercentOtherPS']*Data['TotalRaceDMO']))/Data['TotalRaceE']))

#**************************************************************

Data['WhiteAloneDerivedMOEP'] = (np.sqrt(Data['WhiteAloneNMO']-
                                 (Data['PercentOtherPS']*Data['TotalRaceDMO']))/Data['TotalRaceE'])


Data['WhiteAloneDerivedMOEPR'] = np.where(np.isnan(Data['WhiteAloneDerivedMOEP'])!= True,Data['WhiteAloneDerivedMOEP'],
                            (np.sqrt(Data['WhiteAloneNMO']+
                                 (Data['PercentOtherPS']*Data['TotalRaceDMO']))/Data['TotalRaceE']))

#******************************************************************

Data['HispanicAloneDerivedMOEP'] = (np.sqrt(Data['HispanicAloneNMO']-
                                   (Data['PercentOtherPS']*Data['TotalRaceDMO']))/Data['TotalRaceE'])


Data['HispanicAloneDerivedMOEPR'] = np.where(np.isnan(Data['HispanicAloneDerivedMOEP'])!= True,Data['HispanicAloneDerivedMOEP'],
                            (np.sqrt(Data['HispanicAloneNMO']+
                                   (Data['PercentOtherPS']*Data['TotalRaceDMO']))/Data['TotalRaceE']))


In [88]:
np.where(np.isnan(Data['RaceOtherDerivedMOEP'])) 

(array([118, 279], dtype=int64),)

In [89]:
np.where(np.isnan(Data['RaceOtherDerivedMOEPR'])) 

(array([118, 279], dtype=int64),)

In [90]:
np.where(np.isnan(Data['AsianDerivedMOEPR'])) 

(array([118, 279], dtype=int64),)

In [91]:
np.where(np.isnan(Data['AsianDerivedMOEPR'])) 

(array([118, 279], dtype=int64),)

In [92]:
np.where(np.isnan(Data['BlackAloneDerivedMOEP'])) 

(array([ 42,  81, 118, 144, 204, 279, 291, 328, 346, 413, 432], dtype=int64),)

In [93]:
np.where(np.isnan(Data['BlackAloneDerivedMOEPR'])) 

(array([118, 279], dtype=int64),)

In [94]:
np.where(np.isnan(Data['WhiteAloneDerivedMOEP'])) 

(array([ 85, 118, 119, 279], dtype=int64),)

In [95]:
np.where(np.isnan(Data['WhiteAloneDerivedMOEPR'])) 

(array([118, 279], dtype=int64),)

In [96]:
np.where(np.isnan(Data['WhiteAloneDerivedMOEP'])) 

(array([ 85, 118, 119, 279], dtype=int64),)

In [97]:
np.where(np.isnan(Data['HispanicAloneDerivedMOEP']))

(array([  6,  35,  59,  62,  85, 106, 118, 144, 162, 165, 167, 168, 186,
        209, 236, 268, 279, 287, 291, 304, 325, 328, 349, 421, 437],
       dtype=int64),)

In [98]:
np.where(np.isnan(Data['HispanicAloneDerivedMOEPR']))

(array([118, 279], dtype=int64),)

#### Drove More Than 20 Minutes Derived Proportion MOE

In [99]:
Data['DroveMoreThan20MinutesDerivedMOEP'] = (np.sqrt(Data['DriveMoreThan20MinutesNMO'] 
                                             - (Data['PercentDroveMoreThan20MinutesPS']* 
                                                Data['TotalTransportationDMO']))/Data['TotalTransportationE'])





In [100]:
Data['DroveMoreThan20MinutesDerivedMOEPR'] = np.where(np.isnan(Data['DroveMoreThan20MinutesDerivedMOEP'])!= True,
                                                      Data['DroveMoreThan20MinutesDerivedMOEP'],
                             (np.sqrt(Data['DriveMoreThan20MinutesNMO'] 
                                             + (Data['PercentDroveMoreThan20MinutesPS']* 
                                                Data['TotalTransportationDMO']))/Data['TotalTransportationE']))


In [101]:
np.where(np.isnan(Data['DroveMoreThan20MinutesDerivedMOEP'])) 

(array([  6,  12,  15,  38,  56,  86,  93, 104, 106, 109, 115, 118, 132,
        135, 142, 148, 151, 200, 219, 240, 242, 261, 262, 279, 289, 292,
        293, 295, 307, 317, 322, 330, 336, 339, 342, 345, 351, 385, 390,
        408, 409, 411, 414, 415, 420, 438, 451], dtype=int64),)

In [102]:
np.where(np.isnan(Data['DroveMoreThan20MinutesDerivedMOEPR'])) 

(array([118, 279], dtype=int64),)

#### Percent Private (No School or Pre School) Derived Proportion MOE

In [103]:
Data['PrivateSchoolDerivedMOEP']= (np.sqrt(Data['PrivateNMO']-
                                   (Data['PercentPrivateSchoolPS']*Data['PrivateTotalDMO']))/Data['PrivateTotalA']) 

In [104]:
Data['PrivateSchoolDerivedMOEPR'] = np.where(np.isnan(Data['PrivateSchoolDerivedMOEP'])!= True,
                                                      Data['PrivateSchoolDerivedMOEP'],
                            (np.sqrt(Data['PrivateNMO']+
                                   (Data['PercentPrivateSchoolPS']*Data['PrivateTotalDMO']))/Data['PrivateTotalA'])) 

In [105]:
np.where(np.isnan(Data['PrivateSchoolDerivedMOEP'])) 

(array([  6,  60,  64, 118, 279, 333, 415], dtype=int64),)

In [106]:
np.where(np.isnan(Data['PrivateSchoolDerivedMOEPR'])) 

(array([  6,  60,  64, 118, 279, 333], dtype=int64),)

##### Adults With High School Diploma Derived Proportion MOE

In [107]:
Data['AdultsWithAtLeastBachelorsDerivedMOEP'] = (np.sqrt(Data['AdultsWithAtLeastBachelorsNMO']-
                                                 (Data['PercentAdultsWithAtLeastBachelorsPS']*
                                                          Data['TotalEducationAttainmentDMO']))
                                                 /Data['TotalEducationAttainmentE']) 

In [108]:
Data['AdultsWithAtLeastBachelorsDerivedMOEPR'] = np.where(np.isnan(Data['AdultsWithAtLeastBachelorsDerivedMOEP'])!= True,
                                                     Data['AdultsWithAtLeastBachelorsDerivedMOEP'],
                           (np.sqrt(Data['AdultsWithAtLeastBachelorsNMO']+
                                                 (Data['PercentAdultsWithAtLeastBachelorsPS']*
                                                          Data['TotalEducationAttainmentDMO']))
                                                 /Data['TotalEducationAttainmentE'])) 

##### Adults with At Least Bachelors Degrees Derived Proportion MOE

In [109]:
np.where(np.isnan(Data['AdultsWithAtLeastBachelorsDerivedMOEP'])) 

(array([ 16,  22,  23,  36,  39,  45,  93, 118, 125, 132, 147, 168, 183,
        189, 200, 212, 219, 223, 235, 242, 279, 303, 309, 312, 318, 330,
        334, 340, 345, 352, 366, 382, 384, 405, 407, 408, 409, 444, 449,
        450, 456], dtype=int64),)

In [110]:
np.where(np.isnan(Data['AdultsWithAtLeastBachelorsDerivedMOEPR'])) 

(array([118, 279], dtype=int64),)

In [111]:
Data['HighSchoolDiplomaDerivedMOEP'] = (np.sqrt(Data['HighSchoolDiplomaNMO']-
                                                 (Data['PercentHighSchoolDiplomaPS']*
                                                          Data['TotalEducationAttainmentDMO']))
                                                 /Data['TotalEducationAttainmentE']) 

In [112]:
Data['HighSchoolDiplomaDerivedMOEPR'] = np.where(np.isnan(Data['HighSchoolDiplomaDerivedMOEP'])!= True,
                                                      Data['HighSchoolDiplomaDerivedMOEP'],
                            (np.sqrt(Data['HighSchoolDiplomaNMO']+
                                                 (Data['PercentHighSchoolDiplomaPS']*
                                                          Data['TotalEducationAttainmentDMO']))
                                                 /Data['TotalEducationAttainmentE'])) 

In [113]:
np.where(np.isnan(Data['HighSchoolDiplomaDerivedMOEP'])) 

(array([  3,   7,   8,  12,  13,  15,  16,  17,  22,  23,  25,  27,  28,
         32,  35,  36,  38,  39,  40,  45,  46,  47,  52,  56,  57,  58,
         61,  62,  64,  68,  70,  78,  79,  81,  85,  86,  88,  89,  92,
         94,  97,  99, 101, 104, 105, 106, 108, 109, 111, 114, 115, 118,
        122, 125, 130, 131, 132, 133, 135, 138, 140, 144, 145, 147, 149,
        152, 155, 158, 162, 166, 167, 168, 169, 171, 173, 176, 178, 183,
        187, 188, 191, 195, 198, 200, 202, 203, 206, 212, 214, 223, 225,
        227, 229, 231, 232, 235, 236, 246, 247, 252, 256, 261, 262, 264,
        266, 268, 276, 277, 279, 282, 288, 289, 291, 292, 293, 294, 295,
        299, 300, 303, 307, 309, 312, 316, 318, 322, 323, 325, 330, 335,
        336, 340, 345, 351, 352, 356, 357, 359, 363, 364, 366, 368, 373,
        382, 383, 384, 387, 395, 402, 405, 407, 408, 409, 410, 413, 414,
        421, 423, 426, 432, 437, 441, 444, 449, 450, 451, 452, 453, 454,
        456], dtype=int64),)

In [114]:
np.where(np.isnan(Data['HighSchoolDiplomaDerivedMOEPR'])) 

(array([118, 279], dtype=int64),)

#### Veteran Derived Proportion MOE

In [115]:
Data['VeteranDerivedMOEP'] = (np.sqrt(Data['NoVehicleNMO']-
                                                 (Data['PercentNoVehiclePS']*
                                                          Data['TotalVeteranDMO']))
                                                 /Data['TotalVeteranE'])

In [116]:
Data['VeteranDerivedMOEPR'] = np.where(np.isnan(Data['VeteranDerivedMOEP'])!= True,
                                                    Data['VeteranDerivedMOEP'],
                           (np.sqrt(Data['NoVehicleNMO']+
                                                 (Data['PercentNoVehiclePS']*
                                                          Data['TotalVeteranDMO']))
                                                 /Data['TotalVeteranE']))

In [117]:
np.where(np.isnan(Data['VeteranDerivedMOEP'])) 

(array([  6,  50,  60,  85,  93, 115, 118, 176, 195, 243, 262, 279, 288,
        289, 306, 373], dtype=int64),)

In [118]:
np.where(np.isnan(Data['VeteranDerivedMOEPR'])) 

(array([ 60, 118, 279], dtype=int64),)

####  Employment Derived Proportion MOE

In [119]:
Data['EmployedDerivedMOEP'] = (np.sqrt(Data['EmployedNMO']-
                                                 (Data['PercentEmployedPS']*
                                                          Data['TotalInLaborForceDMO']))
                                                 /Data['TotalInLaborForceE'])

In [120]:
Data['EmployedDerivedMOEPR'] = np.where(np.isnan(Data['EmployedDerivedMOEP'])!= True,
                                                    Data['EmployedDerivedMOEP'],
                          (np.sqrt(Data['EmployedNMO']+
                                                 (Data['PercentEmployedPS']*
                                                          Data['TotalInLaborForceDMO']))
                                                 /Data['TotalInLaborForceE']))

In [121]:
np.where(np.isnan(Data['EmployedDerivedMOEP'])) 

(array([  3,   5,   7,   8,   9,  14,  15,  17,  18,  23,  24,  27,  32,
         40,  45,  47,  48,  54,  65,  67,  68,  70,  75,  76,  78,  83,
         88,  90,  91,  95, 105, 106, 108, 109, 110, 111, 112, 115, 116,
        117, 118, 124, 126, 129, 130, 134, 136, 139, 141, 147, 148, 158,
        159, 166, 171, 176, 186, 188, 194, 198, 202, 205, 207, 209, 210,
        215, 217, 218, 220, 224, 230, 233, 235, 238, 241, 246, 248, 252,
        254, 255, 256, 258, 262, 264, 265, 266, 267, 269, 270, 273, 275,
        278, 279, 283, 285, 290, 292, 297, 303, 306, 312, 316, 319, 320,
        331, 334, 335, 338, 341, 347, 348, 350, 351, 360, 362, 375, 377,
        380, 384, 388, 397, 398, 401, 403, 406, 412, 416, 417, 423, 432,
        441, 444, 447, 451], dtype=int64),)

In [122]:
np.where(np.isnan(Data['EmployedDerivedMOEPR'])) 

(array([118, 279], dtype=int64),)

#### Internet Derived Proportion MOE

In [123]:
Data['BroadbandMOEP'] = (np.sqrt(Data['BroadbandNMO']-
                                                 (Data['PercentInternetAccessPS']*
                                                          Data['TotalBroadbandDMO']))
                                                 /Data['TotalBroadbandE'])

In [124]:
Data['BroadbandMOEPR'] = np.where(np.isnan(Data['BroadbandMOEP'])!= True,
                                                    Data['BroadbandMOEP'],
                          (np.sqrt(Data['BroadbandNMO']+
                                                 (Data['PercentInternetAccessPS']*
                                                          Data['TotalBroadbandDMO']))
                                                 /Data['TotalBroadbandE']))

In [125]:
np.where(np.isnan(Data['BroadbandMOEP'])) 

(array([ 24,  32,  48,  60,  61,  79,  89, 111, 118, 151, 177, 200, 217,
        223, 226, 231, 253, 267, 269, 279, 295, 309, 317, 327, 349, 352,
        380, 442, 444], dtype=int64),)

In [126]:
np.where(np.isnan(Data['BroadbandMOEPR'])) 

(array([ 60, 118, 279], dtype=int64),)

#### Vacancy Derived Proportion MOE

In [127]:
Data['VacantDerivedMOEP'] = (np.sqrt(Data['VacantNMO']-
                                                 (Data['PercentVacantPS']*
                                                          Data['TotalOccupancyDMO']))
                                                 /Data['TotalOccupancyE'])

In [128]:
Data['VacantDerivedMOEPR'] = np.where(np.isnan(Data['VacantDerivedMOEP'])!= True,
                                                   Data['VacantDerivedMOEP'],
                          (np.sqrt(Data['VacantNMO']+
                                                 (Data['PercentVacantPS']*
                                                          Data['TotalOccupancyDMO']))
                                                 /Data['TotalOccupancyE']))

In [129]:
np.where(np.isnan(Data['VacantDerivedMOEP'])) 

(array([ 60, 118, 279], dtype=int64),)

In [130]:
np.where(np.isnan(Data['VacantDerivedMOEPR'])) 

(array([ 60, 118, 279], dtype=int64),)

#### Owner Occupied Derived Proportion MOE

In [131]:
Data['OccupiedMOEP'] = (np.sqrt(Data['OccupiedNMO']-
                                                 (Data['PercentOccupiedPS']*
                                                          Data['TotalOccupancyDMO']))
                                                 /Data['TotalOccupancyE'])

In [132]:
Data['OccupiedMOEPR'] = np.where(np.isnan(Data['OccupiedMOEP'])!= True,
                                                   Data['OccupiedMOEP'],
                          (np.sqrt(Data['OccupiedNMO']+
                                                 (Data['PercentOccupiedPS']*
                                                          Data['TotalOccupancyDMO']))
                                                 /Data['TotalOccupancyE']))

In [133]:
np.where(np.isnan(Data['OccupiedMOEP'])) 

(array([  2,  30,  54,  60,  66,  72, 118, 141, 148, 149, 170, 175, 186,
        193, 220, 222, 258, 262, 263, 264, 279, 292, 323, 343, 347, 374,
        393, 409, 412, 419, 421, 422, 430, 436, 437], dtype=int64),)

In [134]:
np.where(np.isnan(Data['OccupiedMOEPR'])) 

(array([ 60, 118, 279], dtype=int64),)

#### No Vehicle Derived Proportion MOE

In [135]:
Data['NoVehicleDerivedMOEP'] = (np.sqrt(Data['NoVehicleNMO']-
                                                 (Data['PercentNoVehiclePS']*
                                                          Data['TotalVehicleByTenureDMO']))
                                                 /Data['TotalVehicleByTenureE'])

In [136]:
Data['NoVehicleDerivedMOEPR'] = np.where(np.isnan(Data['NoVehicleDerivedMOEP'])!= True,
                                                   Data['NoVehicleDerivedMOEP'],
                         (np.sqrt(Data['NoVehicleNMO']+
                                                 (Data['PercentNoVehiclePS']*
                                                          Data['TotalVehicleByTenureDMO']))
                                                 /Data['TotalVehicleByTenureE']))

In [137]:
np.where(np.isnan(Data['NoVehicleDerivedMOEP'])) 

(array([ 60, 118, 279], dtype=int64),)

In [138]:
np.where(np.isnan(Data['NoVehicleDerivedMOEPR'])) 

(array([ 60, 118, 279], dtype=int64),)

### Take square root of MOE to get their raw values

In [139]:
for row in Data:
    if row not in ('NAME'):
        if row.endswith("M"):
            Data[str(row)] = np.sqrt(Data[str(row)])

### Multiply derived proportion by 100 to get percentages

In [140]:
for row in Data: 
    if row.startswith('Per'):
        Data[str(row)] = Data[str(row)]*100

In [141]:
for row in Data: 
    if row.endswith('MOEPR'):
        Data[str(row)] = Data[str(row)]*100

#### Data Cleaning

- Get a list of columns added during MOE computation, add GEOID columns and delete them

In [142]:
delete = ['Under18MOEZero', 'Under18MOENonZero', 'Over65MOEZero', 
          'Over65MOENonZero', 'OtherMOEZero', 'OtherMOENonZero', 
          'DroveMOEZero', 'DroveMOENonZero', 'PrivateNoSchoolMOEZero', 
          'PrivateNoSchoolMOENonZero', 'PrivateNoSchoolTotalMOEDZero', 'PrivateNoSchoolTotalMOEDNonZero', 
          'HighSchoolDiplomaMOEZero', 'HighSchoolDiplomaMOENonZero', 'AdultsWithAtLeastBachelorsMOEZero',
          'AdultsWithAtLeastBachelorsMOENonZero', 'NoVehicleMOEZero', 'NoVehicleMOENonZero',
          'GEOID2', 'TotalRaceMOED', 'TotalTransportationMOED', 
          'PrivateNoSchoolTotalMOED', 'TotalEducationAttainmentMOED', 
          'TotalVeteranMOED', 'TotalInLaborForceMOED', 'TotalOccupancyMOED', 
          'TotalVehicleByTenureMOED','Under18NMO', 'Over65NMO', 'RaceOtherNMO', 'AsianAloneNMO', 'BlackAloneNMO', 
          'WhiteAloneNMO', 'HispanicAloneNMO', 'DriveMoreThan20MinutesNMO', 
          'PrivateNMO', 'HighSchoolDiplomaNMO',
          'AdultsWithAtLeastBachelorsNMO', 'NoVehicleNMO', 'VeteranNMO','DroveAloneNMO', 
          'EmployedNMO', 'VacantNMO', 'OccupiedNMO','SexbyAgeDMO', 'TotalRaceDMO', 
          'TotalTransportationDMO', 'PercentUnder18PS', 'PercentOver65PS', 'PercentAsianPS',
          'PercentBlackPS', 'PercentWhitePS', 'PercentHispanicPS', 'PercentOtherPS', 'PercentDroveMoreThan20MinutesPS',
          'PercentHighSchoolDiplomaPS', 'PercentAdultsWithAtLeastBachelorsPS', 'PercentPrivateSchoolPS','PercentOwnerOccupiedPS',
          'PercentVeteranPS', 'PercentEmployedPS', 'PercentVacantPS', 'PercentOccupiedPS', 'PercentNoVehiclePS',
          'PrivateTotalDMO', 'TotalEducationAttainmentDMO', 
          'TotalVehicleByTenureDMO', 'TotalVeteranDMO', 'TotalInLaborForceDMO', 'TotalOccupancyDMO']

Data.drop(delete,axis =1, inplace= True)

### Rename Columns 

### Internet

In [143]:
year = '_2020'
margin = '_accuracy'

In [144]:
Data['r88'+year] = Data['BroadbandE']
Data['m88'+year+margin] = Data['BroadbandMOEPR']
Data['d88'+year] = Data['TotalBroadbandE']
Data['m88'+year] = Data['PercentInternetAccess']

#### Sex By Age

#### Population Youth 

In [145]:
Under18E = ['Male_under_5E', 'Male_5_to_9E', 'Male_10_to_14E', 'Male_15_to_17E',
              'Female_under_5E', 'Female_5_to_9E', 'Female_10_to_14E', 'Female_15_to_17E']


Data['r12'+year] = Data[Under18E].sum(1)

Data['d12'+year] = Data['Sex_By_Age_TotalE']

Data['m12'+year] = Data['PercentUnder18']

Data['m12'+year+margin] = Data['Under18DerivedMOEPR']

#### Population Adult

In [146]:
Over65E = ['Male_65_to_66E', 'Male_67_to_69E', 'Male_70_to_74E', 'Male_75_to_79E', 'Male_80_to_84E',
             'Male_85_and_overE', 'Female_65_to_66E', 'Female_67_to_69E', 'Female_70_to_74E', 'Female_75_to_79E',
             'Female_80_to_84E', 'Female_85_and_overE']

Data['r13'+year] = Data[Over65E].sum(1)

Data['d13'+year] = Data['Sex_By_Age_TotalE']

Data['m13'+year] = Data['PercentOver65']

Data['m13'+year+margin] = Data['Over65DerivedMOEPR']

#### Education Attainment 

#### High School Diploma

In [147]:
HighschoolE = ['HighSchoolDiplomaE','GEDorAlternativeE','SomeCollegeLessThan1YearE',
              'SomeCollege1orMoreYearsNoDegreeE','AssociateDegreeE','BachelorsDegreeE',
             'MastersDegreeE','ProfessionalSchoolDegreeE','DoctorateDegreeE']  


Data['r39'+year] = Data[HighschoolE].sum(1)

Data['d39'+year] = Data['TotalEducationAttainmentE']

Data['m39'+year] = Data['PercentHighSchoolDiploma']

Data['m39'+year+margin] = Data['HighSchoolDiplomaDerivedMOEPR']

#### Bachelor's Degree

In [148]:
BachelorsE = ['BachelorsDegreeE','MastersDegreeE','ProfessionalSchoolDegreeE','DoctorateDegreeE']


Data['r20'+year] = Data[BachelorsE].sum(1)

Data['d20'+year] = Data['TotalEducationAttainmentE']

Data['m20'+year] = Data['PercentAdultsWithAtLeastBachelors']

Data['m20'+year+margin] = Data['AdultsWithAtLeastBachelorsDerivedMOEPR']

###### No Vehicle

In [149]:
# NoVehicleE = ['RenterOccupiedNoVehicleE','OwnerOccupiedNoVehicleE']

# Data['NoVehicleA'] = Data[NoVehicleE].sum(1)

In [150]:
# NoVehicleM = ['RenterOccupiedNoVehicleM','OwnerOccupiedNoVehicleM']

# Data['NoVehicleNMO'] = Data[NoVehicleM].sum(1)

# Data['TotalVehicleByTenureDMO'] = Data['TotalVehicleByTenureM']

#### Drove Alone

In [151]:
Data['r10'+year] = Data['DroveAloneE']
Data['m10'+year+margin] = Data['DroveMoreThan20MinutesDerivedMOEPR']

Data['m10'+year] = Data['PercentDroveAlone']

Data['d10'+year] = Data['TotalTransportationE']

#### Veteran

In [152]:
# Data['VeteranNMO'] = Data['VeteranM']
# Data['TotalVeteranDMO'] = Data['TotalVeteranM']

#### Unemployment 

In [153]:
Data['r38'+year] = Data['CivilianInLaborForceEmployedE']
Data['m38'+year+margin] = Data['EmployedDerivedMOEPR']

Data['d38'+year] = Data['TotalInLaborForceE']

Data['m38'+year] = Data['PercentEmployed'] 

##### Race

In [154]:
RaceOtherE = ['AmericanIndianAloneE','NativeHawaiianAloneE','SomeOtherRaceAloneE','TwoorMoreRacesAloneE']
RaceOtherM = ['AmericanIndianAloneM','NativeHawaiianAloneM','SomeOtherRaceAloneM','TwoorMoreRacesAloneM']

Data['r16'+year] = Data['AsianAloneE']
Data['r15'+year] = Data['BlackAloneE']
Data['r14'+year] = Data['WhiteAloneE']
Data['r18'+year] = Data['HispanicAloneE']
Data['r17'+year] = Data[RaceOtherE].sum(1)

Data['m16'+year] = Data['PercentAsian']
Data['m15'+year] = Data['PercentBlack']
Data['m14'+year] = Data['PercentWhite']
Data['m18'+year] = Data['PercentHispanic']
Data['m17'+year] = Data['PercentOther']

Data['d16'+year] = Data['TotalRaceE']
Data['d15'+year] = Data['TotalRaceE']
Data['d14'+year] = Data['TotalRaceE']
Data['d18'+year] = Data['TotalRaceE']
Data['d17'+year] = Data['TotalRaceE']

In [155]:
Data['m16'+year+margin] = Data['AsianDerivedMOEPR']
Data['m15'+year+margin] = Data['BlackAloneDerivedMOEPR']
Data['m14'+year+margin] = Data['WhiteAloneDerivedMOEPR']
Data['m18'+year+margin] = Data['HispanicAloneDerivedMOEPR']
Data['m17'+year+margin] = Data['RaceOtherDerivedMOEPR']

#### Owner Occupied

In [156]:
Data['r29'+year] = Data['OwnerOccupiedE']
Data['m29'+year+margin] = Data['OccupiedMOEPR']
Data['m29'+year] = Data['PercentOwnerOccupied']

Data['d29'+year] = Data['TotalOwnerOccupiedE']

#### Long Commute

In [157]:
CommuteE = ['Drove_20_to_24E', 'Drove_25_to_29E', 'Drove_30_to_34E', 'Drove_35_to_44E', 
                 'Drove_45_to_59E', 'Drove_60_or_MoreE']

Data['r33'+year] = Data[CommuteE].sum(1)



In [158]:
Data['m33'+year+margin] = Data['DroveMoreThan20MinutesDerivedMOEPR']

Data['m33'+year] = Data['PercentDroveMoreThan20Minutes']

Data['d33'+year] = Data['TotalTransportationE']

#### Residential Occupancy

In [159]:
Data['r31'+year] = Data['VacantE']
Data['m31'+year+margin] = Data['VacantDerivedMOEPR']
Data['m31'+year] = Data['PercentVacant'] 

Data['d31'+year] = Data['TotalOccupancyE']

### Exports

In [160]:
UICode = ['r10_2020', 'd10_2020', 'm10_2020', 'm10_2020_accuracy', 'r12_2020','d12_2020','m12_2020','m12_2020_accuracy', 
          'r13_2020', 'd13_2020', 'm13_2020', 'm13_2020_accuracy','r14_2020', 'd14_2020', 'm14_2020', 'm14_2020_accuracy',
          'r15_2020', 'd15_2020', 'm15_2020', 'm15_2020_accuracy','r16_2020', 'd16_2020', 'm16_2020', 'm16_2020_accuracy',
          'r17_2020', 'd17_2020', 'm17_2020', 'm17_2020_accuracy','r18_2020', 'd18_2020', 'm18_2020', 'm18_2020_accuracy',
          'r20_2020', 'd20_2020','m20_2020', 'm20_2020_accuracy','r29_2020', 'd29_2020', 'm29_2020', 'm29_2020_accuracy',
          'r31_2020', 'd31_2020', 'm31_2020', 'm31_2020_accuracy','r33_2020', 'd33_2020', 'm33_2020', 'm33_2020_accuracy',
          'r38_2020', 'd38_2020', 'm38_2020', 'm38_2020_accuracy','r39_2020', 'd39_2020', 'm39_2020', 'm39_2020_accuracy',
          'r88_2020','d88_2020','m88_2020','m88_2020_accuracy']

In [172]:
for row in range(0,len(UICode)-1,4):
    QOLID = pd.DataFrame(Data[UICode[row:row+4]])
    QOLID.to_csv(str(UICode[row][:3])+".csv")

In [162]:
DataUI = pd.DataFrame(Data[UICode])

DataUI.to_csv('QualityofLife2020.csv')

In [163]:
# ## Under18 

# Under18 = ['Male_under_5E', 'Male_under_5M', 'Male_5_to_9E', 'Male_5_to_9M',
#            'Male_10_to_14E', 'Male_10_to_14M', 'Male_15_to_17E', 'Male_15_to_17M', 'Under18MOEN', 
#            'Under18A', 'Under18DerivedMOEP', 'Under18DerivedMOEPR','PercentUnder18','SexbyAgeMOED','Sex_By_Age_TotalE']

# U18 = pd.DataFrame(Data[Under18])
# U18.to_csv('Under18.csv')

# ### Over65

# over65 = ['Male_15_to_17E', 'Male_15_to_17M', 'Male_65_to_66E', 'Male_65_to_66M', 'Male_67_to_69E',
#           'Male_67_to_69M', 'Male_70_to_74E', 'Male_70_to_74M', 'Male_75_to_79E', 'Male_75_to_79M',
#           'Male_80_to_84E', 'Male_80_to_84M', 'Male_85_and_overE','PercentOver65','Sex_By_Age_TotalM',
#           'Male_85_and_overM', 'Over65MOEN', 'Over65A', 'Over65DerivedMOEP', 'Over65DerivedMOEPR']
# O68 = pd.DataFrame(Data[over65])
# O68.to_csv('Over65.csv')


In [164]:
# ### Race 

# Race = ['AmericanIndianAloneM','NativeHawaiianAloneM','AsianAloneM','AsianAloneE','PercentAsian',
#         'SomeOtherRaceAloneM','TwoorMoreRacesAloneM','AmericanIndianAloneE','BlackAloneM','BlackAloneE',
#         'PercentBlack','WhiteAloneM','WhiteAloneE','PercentWhite','HispanicAloneM','HispanicAloneE','PercentHispanic',
#         'NativeHawaiianAloneE','SomeOtherRaceAloneE','PercentOther','TwoorMoreRacesAloneE','TotalRaceM','AsianDerivedMOEPR',
#         'BlackAloneDerivedMOEPR','WhiteAloneDerivedMOEPR','HispanicAloneDerivedMOEPR','RaceOtherDerivedMOEPR'
#        ]

# Race = pd.DataFrame(Data[Race])
# Race.to_csv("Race.csv")

In [165]:
# ## Drove

# Drove = ['DroveAloneE', 'DroveAloneM', 'Drove_20_to_24E', 'Drove_20_to_24M', 'Drove_25_to_29E',
#  'Drove_25_to_29M', 'Drove_30_to_34E', 
#  'Drove_30_to_34M', 'Drove_35_to_44E', 'Drove_35_to_44M', 'Drove_45_to_59E', 
#  'Drove_45_to_59M', 'Drove_60_or_MoreE', 'PercentDroveMoreThan20Minutes',
#  'Drove_60_or_MoreM', 'DroveMoreThan20MinutesMOEN', 
#  'DroveMoreThan20MinutesDerivedMOEP', 'DroveMoreThan20MinutesDerivedMOEPR',
#          'TotalTransportationE','TotalTransportationM']

# Drove20 = pd.DataFrame(Data[Drove])
# Drove20.to_csv("Drove20.csv")

In [166]:
# ## Private School
# Private = ['Kindergaten_TotalMaleE','Grade_1_to_4_TotalMaleE','Grade_5_to_8_TotalMaleE',
#                'Grade_9_to_12_TotalMaleE','Kindergaten_TotalFemaleE','Grade_1_to_4_TotalFemaleE',
#                'Grade_5_to_8_TotalFemaleE','Grade_9_to_12_TotalFemaleE' ,
#           'Kindergaten_MaleE','Grade_1_to_4_MaleE','Grade_5_to_8_MaleE','Grade_9_to_12_MaleE',
#           'Kindergaten_FemaleE','Grade_1_to_4_FemaleE','Grade_5_to_8_FemaleE','Grade_9_to_12_FemaleE',
#            'Kindergaten_MaleM','Grade_1_to_4_MaleM','Grade_5_to_8_MaleM','Grade_9_to_12_MaleM',
#           'Kindergaten_FemaleM','Grade_1_to_4_FemaleM','Grade_5_to_8_FemaleM','Grade_9_to_12_FemaleM',
#           'Kindergaten_TotalMaleM','Grade_1_to_4_TotalMaleM','Grade_5_to_8_TotalMaleM',
#                'Grade_9_to_12_TotalMaleM','Kindergaten_TotalFemaleM','Grade_1_to_4_TotalFemaleM',
#                'Grade_5_to_8_TotalFemaleM','Grade_9_to_12_TotalFemaleM','PercentPrivateSchool' 
#           ]

# Private = pd.DataFrame(Data[Private])
# Private.to_csv("Privateschool.csv")

In [167]:
# ## HighSchool 

# High = ['HighSchoolDiplomaE','GEDorAlternativeE','SomeCollegeLessThan1YearE',
#               'SomeCollege1orMoreYearsNoDegreeE','AssociateDegreeE','BachelorsDegreeE',
#              'MastersDegreeE','ProfessionalSchoolDegreeE','DoctorateDegreeE',
#         'HighSchoolDiplomaM','GEDorAlternativeM','SomeCollegeLessThan1YearM',
#               'SomeCollege1orMoreYearsNoDegreeM','AssociateDegreeM','BachelorsDegreeM',
#              'MastersDegreeM','ProfessionalSchoolDegreeM','DoctorateDegreeM','TotalEducationAttainmentM',
#         'TotalEducationAttainmentE','PercentHighSchoolDiploma','HighSchoolDiplomaDerivedMOEPR'
#        ]  

# High = pd.DataFrame(Data[High])
# High.to_csv("HighSchool.csv")

In [168]:
# ## Bachelors 

# Bachelors =  ['BachelorsDegreeE','MastersDegreeE','ProfessionalSchoolDegreeE',
#               'DoctorateDegreeE','BachelorsDegreeM','MastersDegreeM','ProfessionalSchoolDegreeM',
#               'DoctorateDegreeM','TotalEducationAttainmentM', 'TotalEducationAttainmentE','PercentAdultsWithAtLeastBachelors',
#              'AdultsWithAtLeastBachelorsDerivedMOEP','AdultsWithAtLeastBachelorsDerivedMOEPR']

# Bachelor = pd.DataFrame(Data[Bachelors])
# Bachelor.to_csv("Bachelors.csv")

In [169]:
# ## Veteran

# Veteran = ['VeteranM','TotalVeteranM','VeteranE','PercentVeteran','VeteranDerivedMOEPR']

# Veteran = pd.DataFrame(Data[Veteran] )

# Veteran.to_csv("Veteran.csv")

In [170]:
Data.to_csv('QualityOfLifeExplorer.csv')